version: "3"

services:
  dev:
    build: .
    container_name: mugensweeper-dev
    tty: true
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
    ports:
      - $PORT:$API_PORT
      - $NUXT_PORT:$NUXT_PORT
    links:
      - mongo:mongo
  mongo:
    image: mongo
    container_name: mugensweeper-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mugensweeper-mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:8081

volumes:
  node_modules:
    driver: local
  mongo_data:
    driver: local
