version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test:coverage
      - run:
          command: |
            if [ $CIRCLE_BRANCH = "develop" ] ; then
              yarn coverage
            fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
