version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test:coverage --runInBand
      - run:
          name: Test with current Node.js version
          command: npx --package node@^11 node ./node_modules/.bin/jest --config api/jest.config.js  --runInBand
      - run:
          name: Run a security audit
          command: yarn audit
      - run: yarn coverage

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
